@Host_Address = http://localhost:3000


## Rest API ##
### Test API - GET ###
GET {{Host_Address}}/api/test

### Test API - POST ###
POST {{Host_Address}}/api/test

###==================== Cart API ====================###
### Cart API - GET ###
GET {{Host_Address}}/api/cart

### Cart API - POST ###
POST {{Host_Address}}/api/cart

### Cart API - PUT ###
PUT {{Host_Address}}/api/cart

### Cart API - DELETE ###
DELETE {{Host_Address}}/api/cart

###==================== Submit API ====================###
### Submit API - POST ###
POST {{Host_Address}}/api/submit

{
    "name": "Faii Doe",
    "email": "kookies@gmail.com"
}

###==================== Example API ====================###
### Example API - GET ###
GET {{Host_Address}}/api/example
