@Host_Address = http://localhost:3000


## Rest API ##
### Test API - GET ###
GET {{Host_Address}}/api/test

### Test API - POST ###
POST {{Host_Address}}/api/test

###==================== Cart API ====================###
### Cart API - GET ###
GET {{Host_Address}}/api/cart

### Cart API - POST ###
POST {{Host_Address}}/api/cart

### Cart API - PUT ###
PUT {{Host_Address}}/api/cart

### Cart API - DELETE ###
DELETE {{Host_Address}}/api/cart

###==================== Submit API ====================###
### Submit API - POST ###
POST {{Host_Address}}/api/submit

{
    "name": "Faii Doe",
    "email": "kookies@gmail.com"
}

###==================== Example API ====================###
### Example API - GET ###
GET {{Host_Address}}/api/example

###==================== Cookie Sample API ====================###
### Cookie Sample API - GET ###
GET {{Host_Address}}/api/cookiesample

###==================== Post Blog API ====================###
### Post Blog API - POST ###
POST {{Host_Address}}/api/posts

{
    "title": "Sudatip blog",
    "content": "This is a Sudatip blog content",
    "published": true,
    "author":{
        "name": "ping Doe",
        "email": "ping@example.com"
    }
}

### Post Blog API - GET ###
GET {{Host_Address}}/api/posts

### Post Blog API - GET with title ###
GET {{Host_Address}}/api/posts?title=My Blog2

### Post Blog API - GET by ID ###
GET {{Host_Address}}/api/posts/1

### Post Blog API - PUT ###
PUT {{Host_Address}}/api/posts/1

{
    "title": "My Blog1 Update",
    "content": "This is a pingkunga blog content Update",
    "published": false
}

### Post Blog API - DELETE ###
DELETE {{Host_Address}}/api/posts/2

###==================== User API ====================###'
### User API - GET ###
GET {{Host_Address}}/api/users

